### ISSUE TITLE
[Nightly][STR][1.13.7rc4->1.13.9b0]Options, icon, static/cosmetic filtering broken after WE hybrid migration

### ISSUE THREAD

**Issue by SXZ1** [gorhill/uBlock#2799]
Nightly 19-07-2017, uBO1.13.9b0 from AMO, Win8.1 x64 with latest updates. 

uBO is completely broken after migration to WebExtension hybrid version: Options button in about:addons and icon on the navigation bar are missing, static and cosmetic filtering doesn't work according to raymondhill.net. 

STR:

Launch profile manager, create new profile
Launch Nightly, open new tab, go to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta
Install uBO 1.13.7rc4, click on OK in "uBlock Origin has been added to Nightly" popup
Close the browser
Launch Nightly, Make Nightly default - no, click on uBO icon - Settings
Check "Prevent WebRTC from leaking local IP"
Close uBO settings
Close Nightly

Launch Nightly, enable Menu bar, Tools - Addons - Extensions, click on Gear - "Check for updates"
uBO will update, start counting to 5, uBO should blink during that period of time. Once you say 5, close about:addons and close nightly

Launch Nightly

ER: uBlock icon is on the navigation bar, uBO is fully functional
AR: Options button is missing in about:addons, uBO icon on the navigation bar is missing, network/cosmetic filtering doesn't work according to http://raymondhill.net/ublock/tiles1.html

Disabling/enabling uBO doesn't help. Outdated STR in comment 1 below, you shouldn't use it because it is more complicated.

**Comment by SXZ1** [comment]
STR: 

Launch profile manager, create new profile with title n_ublock_longterm7 
Launch Nightly, open new tab, go to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta
Install uBO 1.13.7rc4, click on OK in "uBlock Origin has been added to Nightly" popup
Close the browser
Launch Nightly, Make Nightly default - no, click on uBO icon - Settings
Check "Prevent WebRTC from leaking local IP", 3rd-party filters - check:
Adblock Warning Removal List, RUS: BitBlock List, RUS: RU AdList

Click on "Apply Changes", click on "Update Now" in order to update filters and switch to "My filters tab" right after that
Paste this text into "My filters" field:

!testskgjskgjskgj
!skdgjskgghrje

Click Apply and close uBO settings
Close Nightly

Launch Nightly, enable Menu bar, Tools - Addons - Extensions, click on Gear - "Check for updates"
uBO will update, start counting to 5, uBO should blink during that period of time. Once you say 5, close about:addons and close nightly

Launch Nightly

ER: uBlock icon is on the navigation bar, uBO is fully functional
AR: Options button is missing in about:addons, uBO icon on the navigation bar is missing, network/cosmetic filtering doesn't work according to http://raymondhill.net/ublock/tiles1.html

Disabling/enabling uBO doesn't help.

Here is video that shows STR:
https://www.youtube.com/watch?v=3ecfzbqiqnA

**Comment by gorhill** [comment]
Anything at the browser console?

**Comment by SXZ1** [comment]
Yes, there are uBO-related entries in the browser console. I marked them with green. Screenshots below. Also, I've just reproduced this bug one more time using str from the first post and comment 1. I can post a video.
![image](https://user-images.githubusercontent.com/26294581/28416421-a031bd5e-6d5c-11e7-9ecd-8db2a4e05c54.png)
![image](https://user-images.githubusercontent.com/26294581/28416431-a74b34e4-6d5c-11e7-8640-e0a6c68c022b.png)

**Comment by SXZ1** [comment]
Here is full screenshot of the browser console:
![image](https://user-images.githubusercontent.com/26294581/28416798-2967077c-6d5e-11e7-9797-882cdf25c237.png)

**Comment by gorhill** [comment]
Looks like there are file access issues? Look at the line "Failed to remove file C:\Users\...\trash\uBlock0@raymondhill.net.xpi". Something on your side is interfering with Firefox's file access?

**Comment by gorhill** [comment]
There is also the line "TypeError: parentDocShell ...", can you expand the stack?

**Comment by SXZ1** [comment]
I have Kaspersky installed, I'll try to figure out if it is the source of the problem. There is one more user on mozillazine forum who reproduced this bug as well: http://forums.mozillazine.org/viewtopic.php?p=14756796#p14756796

Also, Screenshot dev team came across a similar issue, take a look at this comment and proposed solution: https://github.com/mozilla-services/screenshots/issues/3038#issuecomment-315234634
Also, here is the video of me reproducing the bug using str from the first post: https://www.youtube.com/watch?v=rwzfEjCtnDY

I'll expand the stack and post details here.

**Comment by SXZ1** [comment]
In the meanwhile, one more observation: I made a copy of my profile where bug was reproduced and launched this copy using profile manager. uBO 1.13.7rc4 was working normally again in that copied profile! I didn't do anything, just launched that profile! Of course, these two profiles had different names but they were both stored in Firefox\Profiles folder. In other words:

Firefox\Profiles\Profile_where_bug_was_reproduced
Firefox\Profiles\Profile_where_bug_was_reproduced_copy

**Comment by SXZ1** [comment]
About "TypeError: parentDocShell ..." I clicked on tab.js:62:23 and Nightly opened this page. It is pretty long so I uploaded it on imgur: http://i.imgur.com/fcm3YrG.jpg
I don't know if that's what I was meant to do so please write back if I missed something.

**Comment by gorhill** [comment]
My bad, I just realize there is no stack to expand for that error.

On my side I do not have this error either. Do you still have it without uBO installed?

**Comment by SXZ1** [comment]
I've just created new profile, launched it, closed it, launched it and closed it: there is no TypeError in the browser console. Actually, the only error in the browser console is related to telemetry.

Also, I've reproduced this bug after I closed Nightly, closed Kaspersky (there were no Kaspersky-related processes in Task Manager), closed internet connection, connected to the internet again and launched Nightly in order to reproduce the bug.

**Comment by gorhill** [comment]
>  I clicked on tab.js:62:23 and Nightly opened this page.

Just posting the URL of the page is better, all Nightly users have this file on their side.

**Comment by SXZ1** [comment]
URL view-source:resource://devtools/server/actors/tab.js
Marked line: let docShellsEnum = parentDocShell.getDocShellEnumerator(

**Comment by gorhill** [comment]
My understanding is that this source code is related to dev tools. But then, how can dev tools be opened when you launch Nightly, this can only be done afterward. I don't know what to make of this. In any case, it could just be a error which is unrelated to the main issue here.

**Comment by SXZ1** [comment]
I can reproduce this bug in a new profile that I created after I updated to Nightly 20-07-17. However, uBO1.13.9b0 started to function normally in my regular profile that I used to update Nightly from 19-07-17 to 20-07-17 (uBO1.13.9b0 was broken in this profile before I updated to 20-07-17). Strange.

**Comment by SXZ1** [comment]
Screenshots of the browser console from new profile&Nightly 20-07-17, some new errors in there:
http://imgur.com/a/cKmM7

**Comment by gorhill** [comment]
I think all this should be reported to bugzilla, I can't repro and I can't see any failure in uBO itself, the errors reported are outside uBO itself. I don't know what else to make of all this at this point.

**Comment by SXZ1** [comment]
Thank you very much, gorhill! As far as I know, you're using Linux: did you try to reproduce this bug on Windows? Also, I have an account on bugzilla but I think it will be better if you file a bug because I don't understand anything at programming and the only thing I can contribute is STR from the first post.

**Comment by gorhill** [comment]
Could you try your repro steps, but after you update to 1.13.9b0, let your browser idle for a while, just to be sure uBO can complete it's storage conversion before leaving the browser. I would just like to see if this makes a difference, as I wonder what happens if one quit Firefox before uBO completes its storage conversion job.

**Comment by SXZ1** [comment]
I tried to wait for 10 minutes after uBO updated to 1.13.9b0 but that didn't help: uBO was broken after I started Nightly.

**Comment by gorhill** [comment]
Regarding the "access denied" error: <https://bugzilla.mozilla.org/show_bug.cgi?id=1037649>.

**Comment by gorhill** [comment]
I'm trying to investigate as much as possible before opening an issue on bugzilla.

I am wondering if your ublock0.sqlite file could somehow be corrupted in some way, causing the migration code to fail.

**Comment by gorhill** [comment]
I have been trying various things this morning. One thing I tried is to remove all traces of uBO from the profile after removing the extension from the browser.

I launch/quit the browser a couple of time, then I installed uBO/webext from AMO dev channel. The installation failed somehow: though uBO appeared to be install and enabled in `about:addons`, there was no icon in the toolbar, and nothing was getting blocked. Restarting the browser did not solve the issue.

Installing _again_ from AMO without first removing the extension did solve the issue, uBO became functional, with an icon in the toolbar. I had this error reported at the browser console:

```
1500643414524	addons.webextension.uBlock0@raymondhill.net	ERROR	Loading extension 'uBlock0@raymondhill.net': Reading manifest: Background page must be a file within the extension  Log.jsm:752
	App_append resource://gre/modules/Log.jsm:752:9
	log resource://gre/modules/Log.jsm:390:7
	error resource://gre/modules/Log.jsm:398:5
	_logMessage resource://gre/modules/Extension.jsm:373:5
	logError resource://gre/modules/Extension.jsm:369:5
	packagingError resource://gre/modules/Extension.jsm:356:5
	manifestError resource://gre/modules/Extension.jsm:346:5
	BackgroundPage chrome://extensions/content/ext-backgroundPage.js:31:7
	onManifestEntry chrome://extensions/content/ext-backgroundPage.js:68:19
	asyncEmitManifestEntry resource://gre/modules/ExtensionCommon.jsm:920:14
	next self-hosted:1183:9
```

I can reproduce this at will with Nightly 56.0a1 (2017-07-21):

1. uninstall uBO through `about:addons`
1. quit the browser
1. restart the browser
1. install uBO/webext on AMO: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.13.9b0>
    - Result: uBO is broken, not functional
1. Install again from AMO as in step 4
    - Result: uBO is functional

It does not matter whether there is a legacy `ublock0.sqlite` file present or not, so it's unrelated to the migration code. The issue appeats to be with Nightly, and I don't whether this is a new issue with the latest Nightly or whether this is related to the issue filed here.

**Comment by gorhill** [comment]
@SXZ1 Could you see if re-installing on top of the failed installation (as described above) makes uBO/webext work properly?

**Comment by gorhill** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1383064>.

**Comment by gwarser** [comment]
Yesterdey .9 not worked for me.
Today, on Nightly 2017-07-21 I remove .8 -> restarted browser -> installed .9 -> all OK
Then I try to switch directly from .9 to .8 (!) and this bug happens again.

I fixed this somehow by reinstalling again, and after that I cannot reproduce anymore.

**Comment by SXZ1** [comment]
@gorhill 
Long story short: removing and installing uBO1.13.9b0 solved the problem, installing uBO1.13.9b0 on top of uBO1.13.9b0 solved the problem only until the first restart.
I did the following:
Use STR from the first post up to the point of the "Actual results". That means Nightly is launched, uBO is broken
Try to install uBO again using this link https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.13.9b0
uBO1.13.9b0 is functional again but!
I close Nightly and launch it again - uBO is broken again

I close Nightly, launch it again, remove uBO in about:addons and install uBO from here https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.13.9b0
uBO1.13.9b0 is fully functional again
Close Nightly, launch Nightly - uBO1.13.9b0 is still functional.

.

**Comment by SXZ1** [comment]
I can't reproduce bug using STR from this comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1383064#c2

**Comment by SXZ1** [comment]
This comment is wrong, don't read it: https://github.com/gorhill/uBlock/issues/2799#issuecomment-317020092

Here is correct data. 

@gorhill  installing uBO1.13.9b0 on top of uBO1.13.9b0 in broken state solved the problem. Here is what I did:
Use STR from the first post up to the point of the "Actual results". That means Nightly is launched, uBO is broken
Try to install uBO again using this link https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.13.9b0
uBO1.13.9b0 is functional again
Close Nightly and launch it again - uBO is still functional

Now remove uBO in about:addons and install uBO from here right after that without restart https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.13.9b0
uBO1.13.9b0 is fully functional again
Close Nightly, launch Nightly - uBO1.13.9b0 is still functional.

.

**Comment by gorhill** [comment]
No longer relevant. This was a browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1372750>, and now uBO has been fully webext since early September.

**Comment by allo-** [comment]
Happens with Firefox 56.0.2 and uBo 1.14.18 in one profile (in another it does not happen) again.

**Comment by allo-** [comment]
Seems to be fixed after downgrading to 1.14.16 and then installing 1.14.18 again.

Probably still some 1.14.18 bug, because I actually reinstalled the extension because it suddenly removed its icon. After reinstallation no ads were blocked and enabling/disabling the extension adds/removes a tiny bit of whitespace in the toolbar.

Currently it works, I report again if it is missing again after some firefox restarts. I am not sure what caused the change in my profile.

**Comment by gorhill** [comment]
> Probably still some 1.14.18 bug

uBO/webext is not responsible for putting its icon in the toolbar, this is now all handled by the browser.

**Comment by allo-** [comment]
The only thing which still worked was the settings page. Context Menu missing and an adblock test reported that no adblocker is running. The error message on the console and the ctrl-shift-J webconsole was the one in the OP. I uninstalled and reinstalled a few times and removed some ublock files from my profile folder and it did not change anything.
I am surprised that the downgrade and upgrade again fixed it (at least for now). Were there any relevant changes between these releases?

**Comment by gorhill** [comment]
Did you try a refresh of the profile? Apparently a lot of glitches are resolved by doing this: <https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings>. Back up your uBO settings in case something bad happens.

**Comment by allo-** [comment]
No, I did not because my profile was a lot of work ;-). As it currently works lets keep it closed here.
I am just curious why this happened here with that profile when it seemed to be a bug of an older firefox version according to this issue. But I see that there is no point in tracking it as long as there is no clear way to still reproduce it.
