### ISSUE TITLE
A custom filter not working on uBO v1.13.11rc0 / v1.14.0, but working on 1.13.8

### ISSUE THREAD

**Issue by gomoku** [gorhill/uBlock#2938]
Filter issues MUST NOT be reported here. Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

I don't think it's a typical filter issue, because the same filter is working on one version of uBO and not working on another one.

### Describe the issue
A custom exception filter: `@@||*.dcs.redcdn.pl^$domain=dcs.redcdn.pl|www.tvn24.pl`  not working (not bypassing) another (static regex) filter:
`
/(\.log\.|stuk\.|\/st\.gif|\/up\.|js_error|omniuni|2o7|audit\.|log\.(go|js)|mint|(u|smart)target|counter\.|cgi-bin\/counter|sageanalyst|brt\.|[^n]dcs\.|\/counter|touchclarity|directresponse|danasoft|advance\.)/` from
http://hostsfile.mine.nu/downloads/adblock.txt
on website http://www.tvn24.pl/ 
on FF 55.0.3 + uBO v1.13.11rc0 and Opera 47 + uBO v1.14.0
But the custom exception filter working fine on FF 55.0.3 + uBlock Origin v1.13.8
### One or more specific URLs where the issue occurs
http://www.tvn24.pl/ (more websites might be affected, I didn't checked)

### Screenshot in which the issue can be seen
https://s3.dodajfote.pl/2017/08/30/screen108402.png
https://s3.dodajfote.pl/2017/08/30/screen229a09.png

### Steps for anyone to reproduce the issue

1. On a brand fresh browser profile install the affected uBO version
2. In uBO in "3rd party filters" tab untick all filter lists, except "My filters" (just to make sure, but the issue is also reproductible without unticking default filters lists)
3. In uBO in "3rd party filters" tab add http://hostsfile.mine.nu/downloads/adblock.txt
4. In uBO in "My filters" tab add the custom filter.
(instead of 3 & 4 may alternatively load the uBO backup snapshot via uBO "Settings" tab)
5. Apply the settings
6. Visit the website.
7. Notice the lack of images / the custom filter not working
8. Repeat all the steps with uBO 1.13.8
9. Notice the images showing / the filter working fine

### Your settings

- OS/version:  Windows 7 SP1 64bit Ultimate PL
- Browser/version: Firefox 55.0.3 32bit (e10s enabled)  + uBlock Origin version: v1.13.11rc0 
- Browser/version: Opera 47.0.2631.71 64bit (PGO) + uBlock Origin version: v1.14.0

##### Your filter lists

http://hostsfile.mine.nu/downloads/adblock.txt

##### Your custom filters (if any)

`@@||*.dcs.redcdn.pl^$domain=dcs.redcdn.pl|www.tvn24.pl` (more filters might be affected, I didn't checked)

Additional snapshot of backup of uBlock Origin settings:
<details>
```
{
  "timeStamp": 1504122557251,
  "version": "1.13.11rc0",
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "http://hostsfile.mine.nu/downloads/adblock.txt",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "user-filters",
    "http://hostsfile.mine.nu/downloads/adblock.txt"
  ],
  "hiddenSettingsString": "assetFetchTimeout 30\nautoUpdateAssetFetchPeriod 120\nautoUpdatePeriod 7\nignoreRedirectFilters false\nignoreScriptInjectFilters false\nmanualUpdateAssetFetchPeriod 2000\npopupFontSize unset\nsuspendTabsUntilReady false\nuserResourcesLocation unset",
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nmoz-extension-scheme\nopera-scheme\nvivaldi-scheme",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": "@@||*.dcs.redcdn.pl^$domain=dcs.redcdn.pl|www.tvn24.pl\n",
  "filterLists": {
    "assets/user/filters.txt": {
      "off": false
    },
    "http://hostsfile.mine.nu/downloads/adblock.txt": {
      "off": false
    },
    "assets/ublock/filters.txt": {
      "off": true
    },
    "assets/ublock/privacy.txt": {
      "off": true
    },
    "assets/ublock/unbreak.txt": {
      "off": true
    },
    "assets/ublock/badware.txt": {
      "off": true
    },
    "assets/ublock/experimental.txt": {
      "off": true
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "off": true
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "off": true
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "off": true
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "off": true
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "off": true
    }
  }
}
```
<details>

**Comment by gorhill** [comment]
I can reproduce. Investigating.

**Comment by gorhill** [comment]
Fixed in 1.14.2. Thanks for taking the time to file a detailed report.

**Comment by gomoku** [comment]
Np, thanks too for fixing. I've had to fill also another similiar filter issue, but it was too late and I've gone sleep, now I've woke up and I've realised I don't need anymore to fill that another filter issue, because it was being caused by the current issue, thus it has been fixed along with the current issue, by 1.14.3b0. I only post here the affected filters & filters lists, in case it may help you in anyway:

The issue I've filled on the filter list bug issue tracker: 
https://github.com/azet12/PopupBlocker/issues/78

The cosmetic filter  `pl###sidebar-boxes` from filter list: 
https://github.com/azet12/PopupBlocker/blob/master/PPB.txt was not working on https://www.darmoweogłoszenia.pl/, 
thus was not blocking the annoying popup banner at the right side of the webpage, as seen at: https://s3.dodajfote.pl/2017/08/31/screen36c981.png

Also similiar filters were not working:
`.pl###sidebar-boxes `
`www.darmoweogłoszenia.pl###sidebar-boxes` 
`www.xn--darmoweogoszenia-ryc.pl###sidebar-boxes `
`darmoweogłoszenia.pl###sidebar-boxes `
`xn--darmoweogoszenia-ryc.pl###sidebar-boxes `
`darmoweogoszenia-ryc.pl###sidebar-boxes`

Generally putting any domain before the filter was causing the filter not working,for ex. this one this one has been working: `###sidebar-boxes`, the affected filters wern't working on:
Firefox + uBlock Origin 
but were working on:
Opera + uBlock Origin
Firefox + AdBlockPlus

**Comment by gorhill** [comment]
I woke realizing the fix here is not the right fix. I wanted to keep the code change minimal, but the fix here could cause false positives. I will need to go with the less trivial code change.

**Comment by gorhill** [comment]
> The cosmetic filter `pl###sidebar-boxes` from filter list: `https://github.com/azet12/PopupBlocker/blob/master/PPB.txt` was not working on `https://www.darmoweogłoszenia.pl/`

Works for me, both in Chromium and Firefox. Use the logger to diagnose such issue -- it's reported in the logger on my side. It's easy sometimes to forget that we may have switched off cosmetic filtering in the popup panel.

**Comment by gomoku** [comment]
Hey, I've been just right now switching between various versions of uBlock Origin to check some things here and there, and I've realised that something wrong is going on here with that filter issue:

Suddenly now on FF 53.0.3 + uBlock Origin 1.13.8 the affected filter: `@@||*.dcs.redcdn.pl^$domain=dcs.redcdn.pl|www.tvn24.pl`
is working again, and also it has reminded for me now, that the filter indeed has been also working on v1.13.8 before, I just remeber that exactly. So the point is that the filter issue on v1.13.8 happens randomly - the filter sometimes works and sometimes not, which doesn't change the fact it had to be fixed.

As for the another filter issue: `pl###sidebar-boxes`, I'm at 100% sure that's not an issue at my side, I've already also been checking in the loger, but I've checked the issue again right now, and the issue still persist:

 FF 55.0.3 32bit + 
uBlock Origin v1.13.8 the only extension + 
I've even used "Restore defaults button..." + 
then unticked all filter lists except "My filters" where in I've put a single filter: `pl###sidebar-boxes` + clicked "Apply settings" button + 
visit https://www.darmoweogłoszenia.pl/ 

and the banner still popups, in the logger no yellow dom blocked element.

It might be that this filter issue, like the first one, also happens randomly (at least for you), because for me it doesn't - the filter always is not working.

**Comment by gorhill** [comment]
How many filters are reported being enforced in the "3rd-party filters" pane?

**Comment by gorhill** [comment]
Never mind, I can reproduce with 1.13.8/legacy.

**Comment by gorhill** [comment]
Ok the issue was already reported: #1937. It's one of those issue which I just ended up forgetting about. Despite the issue gone with the webext version, I still want to fix it for the sake of whoever still want to use legacy.

**Comment by gorhill** [comment]
Ok, issue is already solved, I just didn't realize it. You just need version 1.13.10+.

**Comment by gomoku** [comment]
Used 1 of 1 of "My filters"

Hey OK, believe what you want, I saw many random nasty bugs in my life. maybe the issue is at my side, maybe not, who knows, I just don't know, I just see what I see and I send it to you. In https://github.com/azet12/PopupBlocker/issues/78 I've asked for help two of my buddies, but after several days no one have replied so far, maybe they're busy, I don't know, so it might be good idea to wait if somebody else is able to reproduce it.

**Comment by gomoku** [comment]
Well, good to see, I also was thinking before in my mind it could be something related to 'ł' in the domain's name. Hmm and looking at https://github.com/azet12/PopupBlocker/issues/78 at:
```
curl: (6) Could not resolve host: www.darmoweogłoszenia.pl
curl: (6) Could not resolve host: darmoweogłoszenia.pl
```
the same issue may happen to cUrl.

**Comment by gomoku** [comment]
On FF 55.0.3 23bit / Opera 47.0.2631.71 64bit (PGO) + 
 uBO v.1.13.10 / v1.14.x  I've notcied that network filters like:
```
! 31.08.2017, 17:37:18 xn--darmoweogoszenia-ryc.pl
||darmoweogłoszenia.pl/pl-mapa.js$script,domain=www.xn--darmoweogoszenia-ryc.pl
```
are not working on non latin domains like https://www.darmoweogłoszenia.pl/

The script is not blocked, in the logger no red blocked script is showing.

The issue is not present in uBO v1.13.8

**Comment by gomoku** [comment]
(uBO v1.14.3b1 webext)

`||darmoweogłoszenia.pl/pl-mapa.js$script,domain=www.xn--darmoweogoszenia-ryc.pl` 
still not working

`pl###sidebar-boxes` fixed, but 
`www.darmoweogłoszenia.pl###sidebar-boxes` still showing empty blank white area.

**Comment by gorhill** [comment]
Unable to reproduce your issues:

![a](https://user-images.githubusercontent.com/585534/29987340-c217d6ba-8f35-11e7-84c6-7f67d3be6463.png)

**Comment by gorhill** [comment]
Ok never mind, I tried with Nightly. I can reproduce with Firefox 55.

**Comment by gorhill** [comment]
This is a Firefox issue really: <https://bugzilla.mozilla.org/show_bug.cgi?id=945240>.

**Comment by gorhill** [comment]
You mind opening a separate issue for the `||darmoweogłoszenia.pl/pl-mapa.js$script,domain=www.xn--darmoweogoszenia-ryc.pl` case?

I want to fix this asap -- I consider this a serious regression, but I want to be able to refer to a separate issue, as it's completely unrelated to the original issue in comment 1. No need to fill it too formally, just fill it with https://github.com/gorhill/uBlock/issues/2938#issuecomment-326658126, except don't import the cosmetic filter issue, that is yet another one, with no real severity.

**Comment by gomoku** [comment]
OK, done: https://github.com/gorhill/uBlock/issues/2950

**Comment by gomoku** [comment]
Just preventively to let you not forget, the last remaining issue to fix is only `darmoweogłoszenia.pl###sidebar-boxes` showing the blank white box when clicked in the logger
