### ISSUE TITLE
This address bild.de

### ISSUE THREAD

**Issue by spec1re** [gorhill/uBlock#821]
https://adblockplus.org/forum/viewtopic.php?f=2&t=41068

@@||sascdn.com^$domain=bild.de
@@||smartadserver.com^$domain=bild.de

Thanks! :)

**Comment by gorhill** [comment]
This

**Comment by chway** [comment]
I'm playing with the **Inline script tag filtering** (I love it.) since few hours and this filter works too:

bild.de##script:contains(ad_smart_site_id)

**Comment by gorhill** [comment]
Ok, I thought OP wanted me to add the filters above -- these were not uBlock Origin-specific so I closed the issue.

Trying the build.de site, I understand they redirect if they detect a blocker. I will add the proper inline script tag: `bild.de##script:contains(/^\s*de.bild.cmsKonfig/)`.

**Comment by gorhill** [comment]
Heh: <http://www.pcworld.com/article/2992434/browsers/sorry-ad-blockers-german-news-site-bild-says-nein.html>:

> Effective Tuesday, anyone attempting to visit Bild.de with an active browser extension such as AdBlock Plus or uBlock origin, will be redirected to a landing page that says (in German), “With an Adblocker activated, you can no longer visit Bild.de.”

**Comment by gorhill** [comment]
Actually, this plain filter works as well:

    ||code.bildstatic.de/*/bild/built/konfig/js/packages/core.js$domain=www.bild.de,script

**Comment by Algorithmus** [comment]
There's now an additional inline script that checks if core.js objects are loaded. You should block it too. Looks something like this:

 (function(){
  var str = '<div style="height:1000px;position:fixed;width:100%;z-index:50000;background-color:#fff; top:20px; left:0;"> <div style="margin:48px auto;width:725px;border:1px solid #ccc;padding: 40px;text-align:center;"><h2 style="font-size:40px;line-height:50px;">Warum sehe ich BILD.de nicht?</h2> <span style="font-size:30px;line-height:40px;color:#454545;">Sie haben Javascript für ihren Browser deaktiviert.<br />Aktivieren Sie Javascript jetzt, um unsere Artikel wieder lesen zu können.</span> </div> </div>'; 
  if(!de || !de.bild || !de.bild.user || !de.bild.env || !de.bild.events) {
   document.querySelector('body').innerHTML = str;
  }
 })();

Not sure what exactly would be the best way to target it without blocking anything else, but I'm sure some form of bild.de##script:contains(...) should work. I'm not on a recent Firefox fork right now.

**Comment by gorhill** [comment]
> There's now an additional inline script that checks if core.js objects are loaded

This was addressed earlier today in this [commit](https://github.com/gorhill/uBlock/commit/6d0fb26766f12ec5853e7055cd3687bc03ccceea).

**Comment by mom20xx** [comment]
suggested solutions like 

```
bild.de##script:contains(/^\s*de.bild.cmsKonfig/) 
bild.de##script:contains(Javascript)
```

are currently not working with ublock origin 1.2.1

for me only this is working with ublock origin 1.2.1

```
bild.de#@#.textAd
bild.de#@#.text_ads
bild.de#@#.text_ad
bild.de#@#.text-ads
bild.de#@#.text-ad-links
bild.de#@#.text-ad
bild.de#@#.pub_728x90
bild.de#@#.pub_300x250m
bild.de#@#.pub_300x250
bild.de###fullBanner
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script
```

**Comment by sluTTYusr** [comment]
None of the solutions suggested above are working with 1.2.1 anymore.

**Comment by gorhill** [comment]
> are currently not working with ublock origin 1.2.1

Works fine from here.

**Comment by sluTTYusr** [comment]
Sorry, for me it still does not work.
Browser is Pale Moon Version: 25.7.3 (x64)

**Comment by gorhill** [comment]
> Sorry, for me it still does not work.

As documented, older versions of Firefox (on which Pale Moon is based) do not support inline script tag filtering. However, wholesale inline script filtering works for Pale Moon, and I confirm this works around Bild's block. See my comment above for Chromium-based browsers, this will also work for Pale Moon.

**Comment by sluTTYusr** [comment]
You are right.
`||www.bild.de^$inline-script` works.
I have the Ghostery add on installed and set it to pause blocking. However, only after disabling the add on the `bild.de` website displays.

**Comment by Hrxn** [comment]
You mean you have Ghostery and uBlock running at the same time?

**Comment by sluTTYusr** [comment]
Yes. Most of the time.

**Comment by Hrxn** [comment]
But why? What are the possible benefits?

**Comment by sluTTYusr** [comment]
Sometimes more is better.
https://www.diffchecker.com/zapbh5b9

**Comment by gorhill** [comment]
> https://www.diffchecker.com/zapbh5b9

The best use for that diff is to see what to block globally using dynamic filtering to get the same result as the other extensions. In this specific case:

- `amazon-adsystem.com`
- `googletagservices.com`
- `optimizely.com`
- `sail-horizon.com`
- `tiqcdn.com`
- `truste.com`

So six global dynamic rules on top of uBO's default settings and you are as well covered -- without the overhead of two extensions which almost completely overlap.

**Comment by seanrand** [comment]
Just FYI, this is starting to get political.

News article In German: http://www.golem.de/news/adblocker-sperre-bild-de-mahnt-youtuber-wegen-erklaervideo-ab-1510-117011.html

> Der Axel-Springer-Verlag verteidigt seine Werbeblockersperre auf den Seiten von Bild.de nun auch mit juristischen Mitteln. In einem Schreiben vom 20. Oktober 2015 mahnt die Kanzlei Lubberger Lehment im Auftrag der Bild GmbH einen Nutzer ab, der auf Youtube.com ein Video veröffentlichte, wie sich die Sperre mit Hilfe von Filterbefehlen in dem Werbeblocker Adblock Plus umgehen lässt. In dem Brief [...] verlangt die Kanzlei eine Unterlassungserklärung und die Zahlung von Anwaltskosten in Höhe von fast 1.800 Euro. Der Gegenstandwert wird mit 50.000 Euro angegeben. Der Verlag bestätigte Golem.de, gegen "alle" vorgehen zu wollen, die die Anti-Adblocker-Initiative "unlauter umgehen".

My rough translation:
> The digital publishing house Axel Springer has now begun to defend its Adblock-block on Bild.de through judicatory means. In a letter from the 20th October 2015, the law office Lubberger Lehment issued a cease and desist order on behalf of Bild GmbH against a Youtube user who published a video explaining how to circumvent the block using Adblock filters and Adblock Plus. In the letter, the law office demands a declaration to cease and desist as well as the payment of lawyer's fees amounting to almost 1800 Euros. The value of dispute is declared as 50000 Euros. The publisher confirmed to Golem.de that it intends to proceed against "anyone" who attempts to circumvent the Adblock-blocking campaign through unfair means.

I couldn't find any articles on this in English, I'll check again in a few days as this news probably hasn't been picked up outside of Germany yet.

Might be time for someone to throw together a blocklist for all Axel Springer websites, similar to murdochblock.info.

Sorry for derailing this, wasn't sure if I should open a non/meta-issue for this but wanted to share.

**Comment by gorhill** [comment]
> a Youtube user who published a video explaining how to circumvent the block using Adblock filters and Adblock Plus

Any link to that Youtube video?

**Comment by seanrand** [comment]
The video has been set to private before I had a chance to watch it.
https://www.youtube.com/watch?v=W7_iPbFXW7I

**Comment by Hrxn** [comment]
> Just FYI, this is starting to get political.

I'd say this is starting to get interesting. Get your popcorn ready. ;-)

> Any link to that Youtube video?

AFAIK, the video just showed how to use the instructions given in the EasyList Germany [thread](https://forums.lanik.us/viewtopic.php?f=90&t=25851) for bild.de.




     
    
And things get even better: http://heise.de/-2854649

Axel Springer won an injunction given by the infamous LG Hamburg (court in Germany known for getting almost everything won :smirk:) against Eyeo (company behind Adblock Plus). Although this is not final, technically.

But I think the angle behind this decision is "interesting", Axel Springer argued that using a blocker against their site is a violation of the German copyright protection law, specifically the section outlawing the circumvention or disabling of copyright protection mechanisms integrated into software.

Here is said law: http://dejure.org/gesetze/UrhG/95a.html

The funny thing is, this has never been used in the context of websites or the web in general. That was definitely not the original intention or scope of that law.

Anyway, I think that bild.de ends up being a useful benchmark for blockers ;-)

**Comment by GoBijan** [comment]
This seems to be the preferred solution nowadays:
@@||bild.de^$elemhide
@@||smartadserver.com/diff/*/partners/$domain=bild.de
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script
